[package]
name = "breathers"
version = "0.5.7"
edition = "2024"
description = "Give rust code breathing room with automatic blank-line spacing"
repository = "https://github.com/0hirume/breathers"
license = "MIT"
keywords = ["formatter", "readability", "rust", "whitespace"]
categories = ["command-line-utilities", "development-tools"]
publish = false

[dependencies]
clang = { version = "2", features = ["runtime"] }
clap = { version = "4", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
console = { version = "0.16", default-features = false, features = ["std"] }
dirs = "7"
globset = { version = "0.4", default-features = false }
indicatif = { version = "0.18", default-features = false }
ra_ap_syntax = "0.0"
regex = { version = "1", default-features = false }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-saphyr = { version = "1", default-features = false, features = ["deserialize"] }
tokio = { version = "1", features = ["io-std", "rt"] }
toml = { version = "1", default-features = false, features = ["parse", "serde", "std"] }
tower-lsp-server = "0.23"
tree-sitter = { version = "0.27", default-features = false }
tree-sitter-cpp = "0.23"
tree-sitter-javascript = "0.25"
tree-sitter-lua = "0.5"
tree-sitter-nu = { git = "https://github.com/nushell/tree-sitter-nu", rev = "4f577aaa735154f934594b598a69ed7b1b707cf6", version = "0.0" }
tree-sitter-pwsh = "0.38"
tree-sitter-python = "0.25"
tree-sitter-typescript = "0.23"
vermis = "0.6"

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[lints.rust]
deprecated_safe = { level = "deny", priority = -1 }
let_underscore = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
unsafe_code = "deny"
unused = { level = "deny", priority = -1 }
warnings = { level = "deny", priority = -1 }
