[package]
name = "breathers"
version = "0.1.0"
edition = "2024"
description = "Give rust code breathing room with automatic blank-line spacing"
repository = "https://github.com/0hirume/breathers"
license = "MIT"
keywords = ["formatter", "readability", "rust", "whitespace"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
ra_ap_syntax = "0.0.351"

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[lints.rust]
deprecated_safe = { level = "deny", priority = -1 }
let_underscore = { level = "deny", priority = -1 }
rust_2018_idioms = { level = "deny", priority = -1 }
unsafe_code = "deny"
unused = { level = "deny", priority = -1 }
warnings = { level = "deny", priority = -1 }
